from pydantic import BaseModel, field_validator
from typing import Optional
from datetime import date, datetime
from domain.tools.sanitizer import sanitize_string
from domain.tools.validators import validar_telefono_venezuela
import re


class Metricas_costoRequest(BaseModel):
    id_vendedor: int = ...
    fecha_captura: str = ...
    ventas_cobradas_total: float = ...
    neto_recibido: float = ...
    cargos_por_venta: float = ...
    costos_envio: float = ...
    inversion_ads: float = ...
    otros_cargos: float = ...
    cargos_envio_full: float = ...
    descuento_reputacion: float = ...

    model_config = {"extra": "forbid"}


class Metricas_costoResponse(Metricas_costoRequest):
    id_metricas_costo: int

    model_config = {"from_attributes": True}