from pydantic import BaseModel, field_validator
from typing import Optional
from datetime import date, datetime
from domain.tools.sanitizer import sanitize_string
from domain.tools.validators import validar_telefono_venezuela
import re


class Metricas_stock_fullRequest(BaseModel):
    id_vendedor: int = ...
    fecha_captura: str = ...
    espacios_p_asignados: int = ...
    espacios_g_asignados: int = ...
    puntaje_calidad: int = ...
    productos_no_aptos_venta: int = ...
    productos_sin_rotacion: int = ...
    productos_antiguedad: int = ...
    productos_exceso_proyeccion: int = ...

    model_config = {"extra": "forbid"}


class Metricas_stock_fullResponse(Metricas_stock_fullRequest):
    id_metricas_stock: int

    model_config = {"from_attributes": True}