from pydantic import BaseModel, field_validator
from typing import Optional
from datetime import date, datetime
from domain.tools.sanitizer import sanitize_string
from domain.tools.validators import validar_telefono_venezuela
import re


class Metricas_negocioRequest(BaseModel):
    id_vendedor: int = ...
    fecha_captura: str = ...
    fecha_inicio_periodo: date = ...
    fecha_fin_periodo: date = ...
    ventas_brutas_moneda_local: float = ...
    ventas_brutas_usd: float = ...
    unidades_vendidas: int = ...
    visitas_totales: int = ...
    intencion_compra: int = ...
    ventas_concretadas: int = ...
    precio_promedio_unidad: float = ...
    precio_promedio_venta: float = ...

    model_config = {"extra": "forbid"}


class Metricas_negocioResponse(Metricas_negocioRequest):
    id_metricas_negocio: int

    model_config = {"from_attributes": True}