from pydantic import BaseModel, field_validator
from typing import Optional
from datetime import date, datetime
from domain.tools.sanitizer import sanitize_string
from domain.tools.validators import validar_telefono_venezuela
import re


class Metricas_reputacionRequest(BaseModel):
    id_vendedor: int = ...
    fecha_captura: str = ...
    ventas_totales_periodo: int = ...
    total_reclamos: int = ...
    total_mediaciones: int = ...
    total_canceladas: int = ...
    total_envios_incorrectos: int = ...
    nivel_reputacion: str = ...
    insignia: Optional[str] = None

    model_config = {"extra": "forbid"}


class Metricas_reputacionResponse(Metricas_reputacionRequest):
    id_metricas_reputacion: int

    model_config = {"from_attributes": True}