from api.controllers.pais import router as pais_router
from api.controllers.moneda import router as moneda_router
from api.controllers.plan_saas import router as plan_saas_router
from api.controllers.vendedor import router as vendedor_router
from api.controllers.publicacion import router as publicacion_router
from api.controllers.reportes_diagnostico import router as reportes_diagnostico_router
from api.controllers.metricas_reputacion import router as metricas_reputacion_router
from api.controllers.metricas_negocio import router as metricas_negocio_router
from api.controllers.metricas_costo import router as metricas_costo_router
from api.controllers.metricas_stock_full import router as metricas_stock_full_router
from api.controllers.metricas_mi_pagina import router as metricas_mi_pagina_router
from api.controllers.rendimiento_publicacion import router as rendimiento_publicacion_router
from api.controllers.metricas_calidad_publicacion import router as metricas_calidad_publicacion_router